all:
	convert +append goldtile.png whitestone.png blackstone.png cursor.png tiles.png
	convert -append tiles.png hex.png hexgame.png
	cp hexgame.png ../../img-src
	echo "Don't forget to change img-src/hexgame.png to indexed mode"

